export type Category = "Echo & Flow" | "Matrix & Grid" | "Circuit & Spark" | "Anchor & Lock";

export interface ActivityStep {
  title: string;
  duration: string;
}

export interface Activity {
  id: string;
  title: string;
  category: Category;
  original_mechanic: string;
  student_steps: ActivityStep[];
  wrap_up_protocol: string;
}

// 50 zero-material activity templates (13 / 13 / 12 / 12)
export const ACTIVITIES: Activity[] = [
  // ---------- Echo & Flow (Language & Reading) ----------
  { id: "ef-01", title: "Whisper Relay", category: "Echo & Flow",
    original_mechanic: "A short sentence is whispered down a chain; the last student says it aloud and the class fixes distortions.",
    student_steps: [
      { title: "Form a single line, shoulder to shoulder", duration: "1 min" },
      { title: "First student receives the target sentence silently", duration: "1 min" },
      { title: "Whisper it once, no repeats, down the chain", duration: "3 min" },
      { title: "Last student announces the version aloud", duration: "1 min" },
      { title: "Class reconstructs the correct sentence together", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand in place. One word each, round-robin, describing what was hardest to keep accurate. Teacher names the linguistic feature that broke down (sound, stress, syntax) and writes nothing — students repeat it aloud three times." },
  { id: "ef-02", title: "Living Sentence", category: "Echo & Flow",
    original_mechanic: "Each student becomes one word and physically rearranges to form valid sentences.",
    student_steps: [
      { title: "Receive one assigned word silently", duration: "1 min" },
      { title: "Cluster by part of speech in corners", duration: "2 min" },
      { title: "Form the longest grammatical sentence possible", duration: "5 min" },
      { title: "Read the sentence aloud in order", duration: "2 min" },
    ],
    wrap_up_protocol: "Sit where you stand. Each student says their word and the role it played. Final beat: the class chants the full sentence twice in unison." },
  { id: "ef-03", title: "Echo Pair Read", category: "Echo & Flow",
    original_mechanic: "Pairs alternate echoing each phrase with controlled prosody.",
    student_steps: [
      { title: "Pair with the nearest partner", duration: "1 min" },
      { title: "Partner A delivers a phrase with intention", duration: "2 min" },
      { title: "Partner B echoes matching pitch and pace", duration: "2 min" },
      { title: "Swap roles for a second pass", duration: "2 min" },
      { title: "Pairs perform a short exchange to the room", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand by your partner. Each pair names one prosodic feature they nailed and one they want to keep practicing. Close with everyone exhaling on a long shared 'shhh' for five seconds." },
  { id: "ef-04", title: "One-Breath Story", category: "Echo & Flow",
    original_mechanic: "A story is built one sentence at a time, each on a single inhalation-to-exhalation.",
    student_steps: [
      { title: "Sit in a circle, eyes closed for one breath", duration: "1 min" },
      { title: "Teacher seeds the opening line", duration: "1 min" },
      { title: "Each student adds one sentence on one breath", duration: "6 min" },
      { title: "Last student closes the story", duration: "2 min" },
    ],
    wrap_up_protocol: "Eyes open. Round-robin: name the sentence you wish you'd said. Close by repeating the final sentence together, slowly." },
  { id: "ef-05", title: "Mirror Diction", category: "Echo & Flow",
    original_mechanic: "Students mirror a partner's mouth shapes silently, then voice the target sounds.",
    student_steps: [
      { title: "Face a partner at arm's length", duration: "1 min" },
      { title: "Mirror mouth shapes silently for target sounds", duration: "3 min" },
      { title: "Add voice while keeping the mirror", duration: "3 min" },
      { title: "Swap leader and follower", duration: "3 min" },
    ],
    wrap_up_protocol: "Drop hands. Each pair names one sound that finally clicked. Class repeats that sound in a single sweep around the room." },
  { id: "ef-06", title: "Hot-Seat Vocab", category: "Echo & Flow",
    original_mechanic: "One student sits facing away; the class describes a target word without using it.",
    student_steps: [
      { title: "Volunteer takes the hot seat", duration: "1 min" },
      { title: "Teacher mouths the word to the rest", duration: "1 min" },
      { title: "Class gives clues, no taboo words", duration: "4 min" },
      { title: "Hot-seat student guesses aloud", duration: "2 min" },
      { title: "Rotate three rounds", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand and stretch. Each former hot-seat student says the word and uses it in a fresh sentence. The class echoes the sentence back." },
  { id: "ef-07", title: "Sound Map", category: "Echo & Flow",
    original_mechanic: "Students close eyes and sort heard words into mental categories by initial sound.",
    student_steps: [
      { title: "Close eyes and sit still", duration: "1 min" },
      { title: "Listen to a slow word stream", duration: "3 min" },
      { title: "Open eyes; move to the corner matching your assigned sound", duration: "2 min" },
      { title: "Group lists every matching word it caught", duration: "3 min" },
    ],
    wrap_up_protocol: "Stay in your corner. Each group shouts its sound and three words in rhythm. Class snaps a single beat between groups." },
  { id: "ef-08", title: "Two-Truths Translate", category: "Echo & Flow",
    original_mechanic: "Pairs trade three statements; partner must paraphrase, not repeat, before judging.",
    student_steps: [
      { title: "Pair up back-to-back", duration: "1 min" },
      { title: "Partner A states two truths and one lie", duration: "2 min" },
      { title: "Partner B paraphrases all three", duration: "2 min" },
      { title: "Partner B guesses the lie", duration: "1 min" },
      { title: "Swap roles", duration: "4 min" },
    ],
    wrap_up_protocol: "Face forward. Each pair names the paraphrase that drifted furthest from the original. Close with one shared rule for accurate retelling." },
  { id: "ef-09", title: "Phrase Sculpting", category: "Echo & Flow",
    original_mechanic: "Students re-say a flat sentence with rising emotional intensity each pass.",
    student_steps: [
      { title: "Stand in a loose semicircle", duration: "1 min" },
      { title: "Teacher offers one neutral sentence", duration: "1 min" },
      { title: "Each student re-says it at +1 intensity", duration: "5 min" },
      { title: "Last student delivers a whisper for contrast", duration: "1 min" },
    ],
    wrap_up_protocol: "Sit on the floor. Round-robin name the emotion you played. Class repeats your version once. End on a collective silent count to three." },
  { id: "ef-10", title: "Silent Storyboard", category: "Echo & Flow",
    original_mechanic: "Students mime story beats; observers narrate aloud in real time.",
    student_steps: [
      { title: "Split into actors and narrators", duration: "1 min" },
      { title: "Actors mime a short sequence in silence", duration: "3 min" },
      { title: "Narrators voice the story as it unfolds", duration: "3 min" },
      { title: "Swap groups and run again", duration: "4 min" },
    ],
    wrap_up_protocol: "Everyone stand. One actor and one narrator pair up and trade the single line they thought captured the scene best. Class chooses the winning line by snap." },
  { id: "ef-11", title: "Rhythm Recall", category: "Echo & Flow",
    original_mechanic: "Key phrases are encoded into clap patterns and recalled days later.",
    student_steps: [
      { title: "Teacher claps a pattern for a key phrase", duration: "1 min" },
      { title: "Class echoes the clap three times", duration: "2 min" },
      { title: "Pairs invent a clap for a second phrase", duration: "4 min" },
      { title: "Whole class performs the medley", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand. Teacher claps; class voices the phrase. Teacher voices a phrase; class claps. End on a unison final clap." },
  { id: "ef-12", title: "Question Ladder", category: "Echo & Flow",
    original_mechanic: "Each student climbs a ladder of questions about a single shared image held in mind.",
    student_steps: [
      { title: "Teacher describes one vivid image aloud", duration: "2 min" },
      { title: "First student asks a literal question", duration: "1 min" },
      { title: "Next asks an inference question", duration: "2 min" },
      { title: "Continue through evaluation and creation rungs", duration: "5 min" },
    ],
    wrap_up_protocol: "Sit. Each student names the rung they found hardest. Class repeats the final creation-level question aloud, in unison." },
  { id: "ef-13", title: "Echo Debate", category: "Echo & Flow",
    original_mechanic: "Before stating a counter-argument, students must accurately echo the opposing point.",
    student_steps: [
      { title: "Split the room into two stances", duration: "1 min" },
      { title: "Side A delivers its claim", duration: "2 min" },
      { title: "Side B echoes the claim verbatim, then counters", duration: "3 min" },
      { title: "Repeat for three exchanges", duration: "5 min" },
    ],
    wrap_up_protocol: "Mix sides. Each student names a point from the other side worth keeping. Close with both sides reading aloud one shared sentence of agreement." },

  // ---------- Matrix & Grid (Math & Logic) ----------
  { id: "mg-01", title: "Floor Grid", category: "Matrix & Grid",
    original_mechanic: "Floor tiles or imagined squares become a coordinate plane students physically occupy.",
    student_steps: [
      { title: "Define origin and axes by pointing", duration: "2 min" },
      { title: "Stand on your assigned coordinate", duration: "2 min" },
      { title: "Apply a transformation and step there", duration: "5 min" },
      { title: "Group debates whether you moved correctly", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand on the origin together. Each student names the transformation they applied and the rule it followed. Final beat: everyone walks one shared transformation in unison." },
  { id: "mg-02", title: "Human Histogram", category: "Matrix & Grid",
    original_mechanic: "Students arrange themselves in columns to represent live class data.",
    student_steps: [
      { title: "Teacher names a measurable trait", duration: "1 min" },
      { title: "Form columns by trait value", duration: "3 min" },
      { title: "Class reads the distribution shape aloud", duration: "3 min" },
      { title: "Predict the shape for a second trait, then form it", duration: "4 min" },
    ],
    wrap_up_protocol: "Sit in your column. Each column states its modal value. End with the class naming whether the distribution was skewed, normal, or bimodal — in one shared word." },
  { id: "mg-03", title: "Number Line Walk", category: "Matrix & Grid",
    original_mechanic: "A line on the floor becomes a number line; students step problems out.",
    student_steps: [
      { title: "Define zero and unit length", duration: "1 min" },
      { title: "Stand on your starting integer", duration: "1 min" },
      { title: "Step the operation given by the teacher", duration: "5 min" },
      { title: "Class confirms or corrects each landing", duration: "4 min" },
    ],
    wrap_up_protocol: "Return to zero. Round-robin name one operation you got right and one that tripped you. End with the whole class stepping +3, −1 in unison." },
  { id: "mg-04", title: "Logic Stand-Off", category: "Matrix & Grid",
    original_mechanic: "Pairs deliver a premise and counter-premise standing toe-to-toe; the class judges validity.",
    student_steps: [
      { title: "Pair up across an imaginary line", duration: "1 min" },
      { title: "Partner A states a premise", duration: "2 min" },
      { title: "Partner B states a conclusion", duration: "2 min" },
      { title: "Class signals valid or invalid by gesture", duration: "3 min" },
      { title: "Swap roles for three more rounds", duration: "4 min" },
    ],
    wrap_up_protocol: "Sit in a circle. Each pair names the fallacy that fooled them most. Class voices the corrected form aloud, in unison." },
  { id: "mg-05", title: "Pattern Pulse", category: "Matrix & Grid",
    original_mechanic: "A sequence is built by hand-claps and snaps; students continue it.",
    student_steps: [
      { title: "Teacher performs the first four terms", duration: "1 min" },
      { title: "Class echoes the pattern twice", duration: "2 min" },
      { title: "Each student adds the next term in turn", duration: "5 min" },
      { title: "Class names the rule aloud", duration: "2 min" },
    ],
    wrap_up_protocol: "Stand. Class performs the full sequence once, slow. Then once, double-speed. End on a single shared snap." },
  { id: "mg-06", title: "Estimation Battle", category: "Matrix & Grid",
    original_mechanic: "Pairs estimate quantities about the room; closest wins a point.",
    student_steps: [
      { title: "Form competing pairs", duration: "1 min" },
      { title: "Teacher poses an estimation question", duration: "1 min" },
      { title: "Pairs whisper their estimate", duration: "2 min" },
      { title: "Reveal estimates and the true value", duration: "2 min" },
      { title: "Run five rounds", duration: "5 min" },
    ],
    wrap_up_protocol: "Sit with partner. Each pair names the heuristic that worked best. End with the class shouting the closest estimate of the day." },
  { id: "mg-07", title: "Set Sort", category: "Matrix & Grid",
    original_mechanic: "Students physically cluster by intersecting attributes to model Venn diagrams.",
    student_steps: [
      { title: "Teacher names two overlapping attributes", duration: "1 min" },
      { title: "Stand in zone A, B, both, or neither", duration: "3 min" },
      { title: "Count each region aloud", duration: "2 min" },
      { title: "Add a third attribute and re-sort", duration: "4 min" },
    ],
    wrap_up_protocol: "Return to the center. Each region names its count and one shared attribute. End with the class voicing the size of the intersection." },
  { id: "mg-08", title: "Probability Coins", category: "Matrix & Grid",
    original_mechanic: "Hands act as coin flips; class aggregates outcomes to compare to theory.",
    student_steps: [
      { title: "Stand with hands behind your back", duration: "1 min" },
      { title: "Choose left or right hand for heads", duration: "1 min" },
      { title: "Reveal in unison; tally heads/tails", duration: "3 min" },
      { title: "Repeat five trials and chart on the air", duration: "5 min" },
    ],
    wrap_up_protocol: "Sit. Class compares observed ratio to 1:1 aloud. End by stating the law of large numbers in one shared sentence." },
  { id: "mg-09", title: "Function Machine", category: "Matrix & Grid",
    original_mechanic: "One student is the secret rule; others input numbers and infer the function.",
    student_steps: [
      { title: "Volunteer holds a secret rule", duration: "1 min" },
      { title: "Class inputs numbers one by one", duration: "5 min" },
      { title: "Volunteer outputs the result aloud", duration: "3 min" },
      { title: "Class guesses the rule", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand. Volunteer announces the rule. Class translates it into both words and symbols, voiced together. Swap volunteer for next round if time." },
  { id: "mg-10", title: "Geometry Body Build", category: "Matrix & Grid",
    original_mechanic: "Small teams form 2D and 3D shapes with their bodies on the floor.",
    student_steps: [
      { title: "Form teams of four", duration: "1 min" },
      { title: "Teacher names a shape", duration: "1 min" },
      { title: "Build the shape with bodies in 30 seconds", duration: "4 min" },
      { title: "Other teams audit angles and edges", duration: "3 min" },
      { title: "Repeat with a 3D shape", duration: "4 min" },
    ],
    wrap_up_protocol: "Sit in your team. Each team names one property of the shape it built (symmetry, vertices, faces). End with the class chanting the property they all share." },
  { id: "mg-11", title: "Algorithm Line", category: "Matrix & Grid",
    original_mechanic: "Each student is one instruction; the class executes the algorithm in order.",
    student_steps: [
      { title: "Receive one instruction silently", duration: "1 min" },
      { title: "Discuss order in pairs", duration: "3 min" },
      { title: "Line up in execution order", duration: "3 min" },
      { title: "Walk through the algorithm with a sample input", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand in order. Each student reads their step aloud. End with a unison shout of the final output." },
  { id: "mg-12", title: "Conjecture Court", category: "Matrix & Grid",
    original_mechanic: "Students propose, test, and convict or acquit mathematical conjectures.",
    student_steps: [
      { title: "Volunteer states a conjecture", duration: "2 min" },
      { title: "Class tests with examples", duration: "4 min" },
      { title: "One student attempts a counter-example", duration: "3 min" },
      { title: "Class votes: proven, refuted, undecided", duration: "3 min" },
    ],
    wrap_up_protocol: "Sit. Each verdict camp names the strongest argument it heard. End with the class voicing the conjecture's status in one word." },
  { id: "mg-13", title: "Mental Math Relay", category: "Matrix & Grid",
    original_mechanic: "Teams pass a running answer; each adds one operation in their head.",
    student_steps: [
      { title: "Form lines of five", duration: "1 min" },
      { title: "First in line receives the seed number", duration: "1 min" },
      { title: "Each whispers their operation and result to the next", duration: "5 min" },
      { title: "Last student announces the final answer", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand in your line. Each student says their operation aloud, in order. Class repeats the final value together." },

  // ---------- Circuit & Spark (High-Energy Movement) ----------
  { id: "cs-01", title: "Corner Stampede", category: "Circuit & Spark",
    original_mechanic: "Four corners hold four answer options; students sprint to their choice.",
    student_steps: [
      { title: "Label the four corners A–D", duration: "1 min" },
      { title: "Teacher poses a question", duration: "1 min" },
      { title: "Sprint to your chosen corner", duration: "2 min" },
      { title: "Each corner defends in one sentence", duration: "4 min" },
      { title: "Run three more rounds", duration: "4 min" },
    ],
    wrap_up_protocol: "Return to center. Each corner names the answer it defended best. End with the class running in place for ten counts to release energy." },
  { id: "cs-02", title: "Energy Tag", category: "Circuit & Spark",
    original_mechanic: "Tagged students freeze in a content-relevant pose; teammates unfreeze them by answering a prompt.",
    student_steps: [
      { title: "Choose two taggers", duration: "1 min" },
      { title: "Tagged students freeze in topic pose", duration: "4 min" },
      { title: "Untagged peers answer a prompt to unfreeze them", duration: "5 min" },
      { title: "Rotate taggers and run again", duration: "3 min" },
    ],
    wrap_up_protocol: "Sit on the floor in a circle. Each student names the pose that meant the most. End with everyone holding the strongest pose for three slow breaths." },
  { id: "cs-03", title: "Stand-Sit Vote", category: "Circuit & Spark",
    original_mechanic: "Standing for agree, sitting for disagree, with rapid statement reads.",
    student_steps: [
      { title: "All stand to begin", duration: "1 min" },
      { title: "Teacher reads ten statements rapidly", duration: "5 min" },
      { title: "Sit or stand on each, no hesitation", duration: "3 min" },
      { title: "Pick the most divisive and discuss in pairs", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand together. Each pair shouts the statement they split on. End with the class jumping once in unison." },
  { id: "cs-04", title: "Speed Sort", category: "Circuit & Spark",
    original_mechanic: "Students sort themselves by an attribute against a clock.",
    student_steps: [
      { title: "Teacher names the sort attribute", duration: "1 min" },
      { title: "Class sorts itself in 60 seconds, no talking", duration: "2 min" },
      { title: "Audit the order out loud", duration: "3 min" },
      { title: "Beat the previous time with a harder attribute", duration: "5 min" },
    ],
    wrap_up_protocol: "Stay in line. Each student says their value aloud, in order. End with the class clapping once for each correct neighbor." },
  { id: "cs-05", title: "Rotation Stations", category: "Circuit & Spark",
    original_mechanic: "Four mental stations rotate every two minutes with movement-based prompts.",
    student_steps: [
      { title: "Form four equal teams", duration: "1 min" },
      { title: "Each team starts at a corner", duration: "1 min" },
      { title: "Perform the station's challenge in 2 min", duration: "8 min" },
      { title: "Rotate clockwise on the bell", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand at your final corner. Each team names the toughest station and one move that worked. End with one shared step clockwise." },
  { id: "cs-06", title: "Body Match-Up", category: "Circuit & Spark",
    original_mechanic: "Students walk the room and pair off whenever a match signal is called.",
    student_steps: [
      { title: "Walk the perimeter at moderate pace", duration: "2 min" },
      { title: "On 'match!' freeze and pair with the nearest peer", duration: "2 min" },
      { title: "Trade one fact, one question, one prediction", duration: "4 min" },
      { title: "Walk again, repeat three rounds", duration: "5 min" },
    ],
    wrap_up_protocol: "Stand still where you froze. Each student names the partner who taught them most and the fact they got. End with one shared step backward." },
  { id: "cs-07", title: "Pulse Quiz", category: "Circuit & Spark",
    original_mechanic: "Heart-rate-raising moves between each question keep cognition warm.",
    student_steps: [
      { title: "Do ten jumping jacks", duration: "1 min" },
      { title: "Answer one question aloud", duration: "1 min" },
      { title: "Five squats", duration: "1 min" },
      { title: "Next question", duration: "1 min" },
      { title: "Continue cycle for ten rounds", duration: "8 min" },
    ],
    wrap_up_protocol: "Stand. Hand on chest, count ten heartbeats together. Each student says one question they answered confidently. Close with a slow exhale." },
  { id: "cs-08", title: "Charades Concept", category: "Circuit & Spark",
    original_mechanic: "Teams act out concepts physically; opponents guess against a clock.",
    student_steps: [
      { title: "Form two teams facing each other", duration: "1 min" },
      { title: "Team A actor draws a concept silently", duration: "1 min" },
      { title: "Act it out, no words, no letters", duration: "3 min" },
      { title: "Team A guesses within 60 seconds", duration: "4 min" },
      { title: "Swap and repeat", duration: "4 min" },
    ],
    wrap_up_protocol: "Sit cross-legged. Each team names the act that landed fastest and why. End with the winning team taking one shared bow." },
  { id: "cs-09", title: "Concept Sprint", category: "Circuit & Spark",
    original_mechanic: "Students sprint to a wall when they recognize a target concept among many.",
    student_steps: [
      { title: "Line up at the back wall", duration: "1 min" },
      { title: "Teacher reads statements; sprint forward only on matches", duration: "5 min" },
      { title: "First to the front wins the round", duration: "2 min" },
      { title: "Run three rounds with rising difficulty", duration: "5 min" },
    ],
    wrap_up_protocol: "Sit at the front wall. Each winner names the cue that triggered the sprint. End with one shared deep breath." },
  { id: "cs-10", title: "Wave Roll-Call", category: "Circuit & Spark",
    original_mechanic: "Students rise and sit in a Mexican wave keyed to category cues.",
    student_steps: [
      { title: "Sit in rows facing the teacher", duration: "1 min" },
      { title: "Teacher calls a category trait", duration: "1 min" },
      { title: "If it applies to you, stand for one count, then sit", duration: "5 min" },
      { title: "Build to chained traits for combined waves", duration: "5 min" },
    ],
    wrap_up_protocol: "Stand. Each row names the trait it saw the biggest wave on. End with one final wave that travels the room once." },
  { id: "cs-11", title: "Mirror Sprint", category: "Circuit & Spark",
    original_mechanic: "Pairs mirror each other's movements while one narrates a concept.",
    student_steps: [
      { title: "Face a partner at arm's length", duration: "1 min" },
      { title: "Leader moves slowly; follower mirrors", duration: "3 min" },
      { title: "Leader narrates a process while moving", duration: "4 min" },
      { title: "Swap roles", duration: "4 min" },
    ],
    wrap_up_protocol: "Drop hands. Each pair names the moment the mirror broke and what it taught them. End with both partners taking one synchronized step back." },
  { id: "cs-12", title: "Sound Sprint", category: "Circuit & Spark",
    original_mechanic: "Students move at a pace matching the rhythm called by the teacher.",
    student_steps: [
      { title: "Stand in scattered formation", duration: "1 min" },
      { title: "Teacher claps a tempo", duration: "1 min" },
      { title: "Move feet at that tempo while answering prompts", duration: "5 min" },
      { title: "Tempo rises every minute", duration: "5 min" },
    ],
    wrap_up_protocol: "Stop on the final clap. Each student names the tempo at which thinking got hardest. End with the class clapping the slowest tempo together." },

  // ---------- Anchor & Lock (Synthesizers & Closings) ----------
  { id: "al-01", title: "Three-Word Lock", category: "Anchor & Lock",
    original_mechanic: "Each student leaves with three words that anchor the lesson.",
    student_steps: [
      { title: "Sit quietly and review the lesson silently", duration: "2 min" },
      { title: "Write your three words in the air", duration: "1 min" },
      { title: "Share with a partner", duration: "3 min" },
      { title: "Vote on the class's three", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand. Class chants the three winning words in unison, three times. Last chant is whispered. Sit on the silence." },
  { id: "al-02", title: "One Question Out", category: "Anchor & Lock",
    original_mechanic: "Each student voices a single lingering question before leaving.",
    student_steps: [
      { title: "Sit in a circle", duration: "1 min" },
      { title: "Think of your strongest remaining question", duration: "2 min" },
      { title: "Each student voices it in order", duration: "5 min" },
      { title: "Vote on the question worth opening tomorrow", duration: "2 min" },
    ],
    wrap_up_protocol: "Stand on the chosen question. Each student says it together once. Teacher names tomorrow's opening move based on it. Class exhales as one." },
  { id: "al-03", title: "Headline Recap", category: "Anchor & Lock",
    original_mechanic: "Students compose newspaper headlines for the lesson and read them aloud.",
    student_steps: [
      { title: "Think in silence for one minute", duration: "1 min" },
      { title: "Compose a 7-word headline in your head", duration: "3 min" },
      { title: "Pair-share two headlines", duration: "3 min" },
      { title: "Pairs publish to the room", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand. Class votes the front-page headline by snapping. Winner repeats it twice. Class chants it once together." },
  { id: "al-04", title: "Anchor Pose", category: "Anchor & Lock",
    original_mechanic: "Each student adopts a posture they will associate with the lesson's core idea.",
    student_steps: [
      { title: "Stand in space", duration: "1 min" },
      { title: "Pick a pose for the core concept", duration: "2 min" },
      { title: "Hold it while naming the concept silently", duration: "3 min" },
      { title: "Walk and re-pose on cue three times", duration: "4 min" },
    ],
    wrap_up_protocol: "Hold your pose. Round-robin name the concept your pose anchors. End with everyone releasing the pose on a shared exhale." },
  { id: "al-05", title: "Whisper Close", category: "Anchor & Lock",
    original_mechanic: "The final summary is whispered around the circle and re-emerges at the start.",
    student_steps: [
      { title: "Form a tight circle", duration: "1 min" },
      { title: "Teacher whispers the summary to one student", duration: "1 min" },
      { title: "Whisper it onward once each", duration: "5 min" },
      { title: "Last student says it aloud", duration: "2 min" },
    ],
    wrap_up_protocol: "Stay in circle. Class compares the original and the final version. Agree on the correct sentence. Repeat it in unison once, quietly." },
  { id: "al-06", title: "Pair Quiz Lock", category: "Anchor & Lock",
    original_mechanic: "Pairs quiz each other on three closing questions agreed by the class.",
    student_steps: [
      { title: "Vote on three closing questions", duration: "3 min" },
      { title: "Pair up", duration: "1 min" },
      { title: "Quiz each other on all three", duration: "5 min" },
      { title: "Identify the toughest one", duration: "2 min" },
    ],
    wrap_up_protocol: "Stand with partner. Each pair names the question that nearly stumped them. Class answers it together aloud. Pairs shake hands and part." },
  { id: "al-07", title: "Future Self Note", category: "Anchor & Lock",
    original_mechanic: "Students compose a verbal note for tomorrow's self to lock the lesson.",
    student_steps: [
      { title: "Close eyes for one breath", duration: "1 min" },
      { title: "Whisper a one-sentence note to your future self", duration: "3 min" },
      { title: "Tell a partner the note exactly", duration: "3 min" },
      { title: "Partner promises to recall it tomorrow", duration: "3 min" },
    ],
    wrap_up_protocol: "Open eyes. Each student names the note their partner promised to keep. Class agrees on one shared note for all. Repeat it together once." },
  { id: "al-08", title: "Stop, Start, Keep", category: "Anchor & Lock",
    original_mechanic: "Each student names one behavior to stop, start, and keep after the lesson.",
    student_steps: [
      { title: "Reflect silently on the lesson", duration: "2 min" },
      { title: "Decide your stop/start/keep trio", duration: "3 min" },
      { title: "Share in groups of four", duration: "4 min" },
      { title: "Group reports the strongest trio", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand in your group. Each group voices its trio. Class chooses one shared 'keep' to repeat aloud together. End on its third repetition." },
  { id: "al-09", title: "Counter-Argument Lock", category: "Anchor & Lock",
    original_mechanic: "Students lock learning by voicing the strongest counter to the day's claim.",
    student_steps: [
      { title: "Restate the day's claim aloud together", duration: "1 min" },
      { title: "Think of the strongest counter", duration: "3 min" },
      { title: "Share counter with a partner", duration: "3 min" },
      { title: "Class names the most challenging counter", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand. Class voices the counter once, the claim once, and the resolution once — in that order. End with one shared nod." },
  { id: "al-10", title: "Echo Summary", category: "Anchor & Lock",
    original_mechanic: "The teacher gives the summary; the class echoes it in three falling volumes.",
    student_steps: [
      { title: "Stand and face the teacher", duration: "1 min" },
      { title: "Teacher voices the summary loudly", duration: "1 min" },
      { title: "Class echoes in normal volume", duration: "2 min" },
      { title: "Echo whisper, then mouth silently", duration: "3 min" },
      { title: "Sit on the silent echo", duration: "1 min" },
    ],
    wrap_up_protocol: "Stay seated. Each student names one word that lodged in memory. Class voices the full summary together one last time, at speaking volume." },
  { id: "al-11", title: "Two-Minute Teach", category: "Anchor & Lock",
    original_mechanic: "Pairs teach each other the lesson in exactly two minutes, then audit.",
    student_steps: [
      { title: "Pair up", duration: "1 min" },
      { title: "Partner A teaches for 2 minutes", duration: "3 min" },
      { title: "Partner B audits and corrects", duration: "3 min" },
      { title: "Swap roles", duration: "4 min" },
    ],
    wrap_up_protocol: "Stand with partner. Each pair names the part they taught best and the gap they closed. End with both partners taking one slow shared breath." },
  { id: "al-12", title: "Closing Rituals Circle", category: "Anchor & Lock",
    original_mechanic: "A repeated weekly closing chant anchors lessons over time.",
    student_steps: [
      { title: "Form a circle, hands at sides", duration: "1 min" },
      { title: "Teacher leads the four-line chant", duration: "2 min" },
      { title: "Class repeats it three times", duration: "4 min" },
      { title: "Each student adds one word reflecting the day", duration: "3 min" },
    ],
    wrap_up_protocol: "Stand still in circle. Class chants the four lines plus today's added words once. End on a single shared clap, then disperse in silence." },
];

export const CATEGORIES: Category[] = ["Echo & Flow", "Matrix & Grid", "Circuit & Spark", "Anchor & Lock"];

export function categoryColor(c: Category) {
  switch (c) {
    case "Echo & Flow": return "echo";
    case "Matrix & Grid": return "matrix";
    case "Circuit & Spark": return "circuit";
    case "Anchor & Lock": return "anchor";
  }
}
