import type { Category } from "./activities";

export interface GameInstruction {
  step: string;
  duration: string;
}

export interface Game {
  id: string;
  title: string;
  category: Category;
  pitch: string;
  group_size: string;
  total_duration: string; // ~30 min
  instructions: GameInstruction[];
  scoring_or_win: string;
  variations: string[];
  source_note: string;
}

// 50 zero-material 30-minute classroom games.
// Sourced & adapted from publicly documented teacher-game catalogs:
// Edutopia "100+ Energizers" lists, British Council TeachingEnglish games,
// Cambridge ESOL classroom activity bank, Kagan cooperative structures,
// PE Central no-equipment games, NCTM math discourse routines,
// Project Zero thinking routines, Mindfulness in Schools Project (.b).
// Mechanics are paraphrased — no proprietary text reproduced.
export const GAMES: Game[] = [
  // ============ Echo & Flow (Language / Reading / Discussion) ============
  {
    id: "g-ef-01", title: "Word Association Marathon", category: "Echo & Flow",
    pitch: "A rolling 30-minute chain of associations forced to stay inside the lesson's semantic field.",
    group_size: "Whole class, circle.", total_duration: "30 min",
    instructions: [
      { step: "Stand in a circle. Teacher names the topic and three banned generic words (e.g. 'thing', 'stuff', 'good').", duration: "3 min" },
      { step: "Teacher seeds the first lesson-related word. Each student in turn says one word associated with the previous one and connected to the lesson.", duration: "4 min" },
      { step: "Round 2: same chain, but each student must justify the link in five words or fewer.", duration: "6 min" },
      { step: "Round 3: any student may challenge a link; class votes thumbs-up/down. Broken links cost the chain one life (max three lives).", duration: "8 min" },
      { step: "Round 4 (speed): 20 seconds per student, no challenges, recording the chain aloud.", duration: "6 min" },
      { step: "Debrief: name three words that surprised you and one that opened a new angle on the topic.", duration: "3 min" },
    ],
    scoring_or_win: "Chain survives all four rounds with at least one life remaining.",
    variations: ["Restrict to one part of speech.", "Require every fifth word to be a question."],
    source_note: "Adapted from the British Council 'Word Tennis' family of warmers.",
  },
  {
    id: "g-ef-02", title: "Silent Debate", category: "Echo & Flow",
    pitch: "A full debate carried out in pantomime and choral response — argumentation without speech.",
    group_size: "Pairs across two facing rows.", total_duration: "30 min",
    instructions: [
      { step: "Two rows face each other. Teacher posts the motion aloud. Sides take 'For' and 'Against' by row.", duration: "3 min" },
      { step: "Each pair invents a silent gesture for their core argument (60 seconds).", duration: "4 min" },
      { step: "Round 1: For row performs all gestures in sequence; Against row mirrors then performs a counter-gesture.", duration: "6 min" },
      { step: "Round 2: pairs swap partners by sliding one seat right; each must read the new partner's gesture aloud in one sentence before answering with their own gesture.", duration: "8 min" },
      { step: "Round 3 (verdict): class forms a continuum line by how convinced they are; anyone may move once and must voice the gesture that moved them.", duration: "6 min" },
      { step: "Debrief: name the strongest non-verbal argument you saw.", duration: "3 min" },
    ],
    scoring_or_win: "Majority shift on the continuum line names the winning side.",
    variations: ["Allow one whispered sentence per round.", "Run as small-group fishbowls."],
    source_note: "Inspired by Liberating Structures 'Conversation Café' and drama warmups.",
  },
  {
    id: "g-ef-03", title: "Story Spine Relay", category: "Echo & Flow",
    pitch: "Teams co-build a narrative using the Pixar spine — strictly oral, no notes.",
    group_size: "Teams of 5.", total_duration: "30 min",
    instructions: [
      { step: "Teach the spine: Once upon a time / Every day / Until one day / Because of that / Until finally / Ever since then.", duration: "4 min" },
      { step: "Each team assigns one beat to each member. Teacher gives a lesson-topic anchor object/concept.", duration: "3 min" },
      { step: "Round 1: each team performs their story aloud in 90 seconds.", duration: "8 min" },
      { step: "Round 2: teams rotate one member; the new member must re-tell the team's story preserving all six beats.", duration: "7 min" },
      { step: "Round 3 (constraint): one beat must be told as a question; another must include a number; another must include a feeling.", duration: "6 min" },
      { step: "Debrief: which beat was the hardest to keep faithful and why?", duration: "2 min" },
    ],
    scoring_or_win: "Class votes: best-preserved, most-creative, clearest topic link.",
    variations: ["Run silently with mime.", "Restrict to past simple verbs only."],
    source_note: "Pixar Story Spine, popularised by Kenn Adams and used in EAL classrooms.",
  },
  {
    id: "g-ef-04", title: "Just-a-Minute (Lesson Edition)", category: "Echo & Flow",
    pitch: "BBC-style speak-for-60-seconds without hesitation, repetition or deviation — on lesson terms.",
    group_size: "Whole class, rotating speakers.", total_duration: "30 min",
    instructions: [
      { step: "Explain the three faults: hesitation (>1s pause), repetition (any content word), deviation (off-topic). Demonstrate.", duration: "4 min" },
      { step: "Topic pool: 12 lesson-related prompts on the board. First speaker draws one and begins.", duration: "2 min" },
      { step: "Others raise a hand to challenge; if upheld, challenger takes over the remaining seconds on the same topic.", duration: "10 min" },
      { step: "Speaker who is talking when the minute ends scores 2 points; a successful challenge scores 1.", duration: "—" },
      { step: "Round 2: speakers must include one date, one cause, one effect.", duration: "8 min" },
      { step: "Final round: champions face off head-to-head on a teacher's choice topic.", duration: "4 min" },
      { step: "Debrief: which words/phrases were 'lifesavers' to avoid hesitation?", duration: "2 min" },
    ],
    scoring_or_win: "Highest cumulative points wins the 'Minute Master' title.",
    variations: ["90 seconds for advanced groups.", "Pair format: tag-team minute."],
    source_note: "Format from BBC Radio 4 'Just a Minute', widely adapted by ESL teachers.",
  },
  {
    id: "g-ef-05", title: "Taboo Without Cards", category: "Echo & Flow",
    pitch: "Describe a lesson term to your team without using five forbidden words your opponents whisper.",
    group_size: "Two teams of 6–10.", total_duration: "30 min",
    instructions: [
      { step: "Form two teams. Each team brainstorms 20 lesson terms and 5 'taboo' words for each (5 min).", duration: "5 min" },
      { step: "Team A's clue-giver faces their team; Team B whispers the term plus its five taboo words to the clue-giver.", duration: "3 min" },
      { step: "Clue-giver has 60 seconds per term, can pass twice. Saying a taboo word = skip + 0 points.", duration: "—" },
      { step: "Run 6 turns per team, rotating clue-givers.", duration: "16 min" },
      { step: "Bonus round: clue-giver can only use gestures + numbers.", duration: "4 min" },
      { step: "Debrief: which taboo words were hardest to avoid and why are they cognitively 'sticky'?", duration: "2 min" },
    ],
    scoring_or_win: "1 point per correct guess. Highest total wins.",
    variations: ["Solo speed mode.", "Pictionary-style mime hybrid."],
    source_note: "Mechanic from Hasbro's Taboo; classroom adaptation is standard ELT practice.",
  },
  {
    id: "g-ef-06", title: "Concept Charades", category: "Echo & Flow",
    pitch: "Abstract lesson concepts must be embodied — no words, no sound, only the body.",
    group_size: "Teams of 4.", total_duration: "30 min",
    instructions: [
      { step: "Teacher posts 16 abstract concepts from the lesson (e.g. inflation, metaphor, equilibrium).", duration: "2 min" },
      { step: "Teams draft an order. Round 1: solo mime, 45-second guess window.", duration: "10 min" },
      { step: "Round 2: 'sculpture' mode — actor poses three teammates as a frozen tableau, no movement, 60 seconds.", duration: "10 min" },
      { step: "Round 3: 'machine' mode — full team builds a moving 6-part machine that represents the concept.", duration: "6 min" },
      { step: "Debrief: which concept was easier to feel than to define?", duration: "2 min" },
    ],
    scoring_or_win: "Points per correct guess; bonus 2 points for unanimous tableau recognition.",
    variations: ["Only hands.", "Add a one-word title at the end."],
    source_note: "Drama-in-education tradition (Dorothy Heathcote tableaux).",
  },
  {
    id: "g-ef-07", title: "Two-Sided Story Circle", category: "Echo & Flow",
    pitch: "The same story is retold twice — once optimistically, once tragically — to surface perspective.",
    group_size: "Circle of 8–16.", total_duration: "30 min",
    instructions: [
      { step: "Teacher seeds one neutral opening line tied to the lesson.", duration: "2 min" },
      { step: "Round 1: clockwise, each student adds one sentence framing events positively.", duration: "8 min" },
      { step: "Round 2: counter-clockwise from the same opening, each adds a sentence framing the same events tragically.", duration: "8 min" },
      { step: "Round 3: alternate optimist/pessimist sentences — students must yield to the opposite framing every other turn.", duration: "8 min" },
      { step: "Debrief: which framing felt truer to the topic and why?", duration: "4 min" },
    ],
    scoring_or_win: "No score — success is two coherent endings from one beginning.",
    variations: ["Three framings: optimist, pessimist, neutral observer."],
    source_note: "Adapted from Project Zero 'Circle of Viewpoints' thinking routine.",
  },
  {
    id: "g-ef-08", title: "Hot Seat Press Conference", category: "Echo & Flow",
    pitch: "One student becomes a lesson concept and is interviewed by the press (the class).",
    group_size: "Whole class + 1 hot-seat.", total_duration: "30 min",
    instructions: [
      { step: "Volunteer chooses (or draws) a lesson concept/person and takes the chair.", duration: "2 min" },
      { step: "Class prepares 3 questions each in pairs: factual, inferential, evaluative.", duration: "5 min" },
      { step: "Press conference round 1: 8 minutes of rotating questions; hot-seat must stay in character.", duration: "8 min" },
      { step: "Swap hot-seat; second volunteer takes a contrasting concept.", duration: "1 min" },
      { step: "Round 2: same format, plus interviewers must paraphrase the prior answer before asking a new question.", duration: "8 min" },
      { step: "Debrief: which questions exposed the concept most? Which answers surprised you?", duration: "6 min" },
    ],
    scoring_or_win: "Class nominates 'most-in-character' and 'sharpest question'.",
    variations: ["Pair hot-seat for shy students.", "Add a 'fact-check' student with veto power."],
    source_note: "Hot-seating is a Heathcote drama convention used in history/literature classes.",
  },
  {
    id: "g-ef-09", title: "Lesson Headlines", category: "Echo & Flow",
    pitch: "Pairs compose tabloid, broadsheet, and academic headlines for today's content — out loud, in 30 minutes.",
    group_size: "Pairs.", total_duration: "30 min",
    instructions: [
      { step: "Demo three headline registers: tabloid (shock), broadsheet (precise), academic (qualified).", duration: "5 min" },
      { step: "Pairs receive (or pick) three lesson sub-topics; for each, draft one headline in each register, spoken aloud only.", duration: "12 min" },
      { step: "Pairs perform their nine headlines to another pair; listening pair guesses which register is which.", duration: "8 min" },
      { step: "Whole-class 'newsroom': best of each register is chanted by the class three times.", duration: "3 min" },
      { step: "Debrief: which register distorts the lesson most? Which is most useful?", duration: "2 min" },
    ],
    scoring_or_win: "Class vote per register category.",
    variations: ["Add a 'meme caption' register.", "Translate into a second language for bilingual rooms."],
    source_note: "Headline routine from Project Zero 'Headlines' thinking routine.",
  },
  {
    id: "g-ef-10", title: "Accent & Register Roulette", category: "Echo & Flow",
    pitch: "Same lesson sentence delivered through random accent/register combos to study prosody.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Teacher and class brainstorm 8 registers (formal, sports commentator, conspiracy theorist…) and 8 contexts (boardroom, playground…).", duration: "5 min" },
      { step: "Teacher provides three lesson sentences.", duration: "2 min" },
      { step: "Each student rolls (or is assigned) one register + one context and performs one sentence.", duration: "12 min" },
      { step: "Listeners guess register/context after each turn.", duration: "—" },
      { step: "Pair round: same sentence as a dialogue between two registers.", duration: "8 min" },
      { step: "Debrief: which register made the content easiest/hardest to understand?", duration: "3 min" },
    ],
    scoring_or_win: "1 point per correct register guess.",
    variations: ["Use only volume changes for younger learners."],
    source_note: "Inspired by Augusto Boal's Theatre of the Oppressed voice work.",
  },
  {
    id: "g-ef-11", title: "Six-Word Memoir Slam", category: "Echo & Flow",
    pitch: "Compress today's lesson into a six-word memoir, then perform it.",
    group_size: "Individual → group.", total_duration: "30 min",
    instructions: [
      { step: "Show two famous six-word memoirs as models (recited).", duration: "3 min" },
      { step: "Each student silently composes three six-word memoirs about the lesson.", duration: "7 min" },
      { step: "Triads share, choose the strongest from each member, refine collectively.", duration: "8 min" },
      { step: "Slam round: each student performs their final memoir to the class with one expressive choice (pause, volume, gesture).", duration: "8 min" },
      { step: "Class snaps for top 3; winners recite once more in unison with the room.", duration: "2 min" },
      { step: "Debrief: which word did the most work in your memoir?", duration: "2 min" },
    ],
    scoring_or_win: "Class snap-vote selects top 3.",
    variations: ["Strict: exactly six words.", "Bilingual: 3 words per language."],
    source_note: "Six-word memoir form attributed to SMITH Magazine, used widely in ELA.",
  },
  {
    id: "g-ef-12", title: "Devil's Advocate Carousel", category: "Echo & Flow",
    pitch: "Students rotate through five stations each holding a different stance toward the lesson claim.",
    group_size: "Groups of 5, five corners.", total_duration: "30 min",
    instructions: [
      { step: "Teacher posts one provocative claim about the lesson and 5 stances: Supporter, Skeptic, Historian, Beneficiary, Outsider.", duration: "4 min" },
      { step: "Each group starts at one stance and prepares its 60-second argument.", duration: "5 min" },
      { step: "Rotate every 4 minutes; new group must voice the previous group's argument back before adding their own.", duration: "20 min" },
      { step: "Final whip-around: each student names the stance that shifted their thinking most.", duration: "1 min" },
    ],
    scoring_or_win: "No score — success = every group can fairly state every stance.",
    variations: ["Use a single chair rotation for small classes."],
    source_note: "Variant of Kagan 'RoundRobin' + Harkness discussion seeding.",
  },
  {
    id: "g-ef-13", title: "Living Dictionary", category: "Echo & Flow",
    pitch: "The class becomes a dictionary of today's vocabulary — each student a definable entry.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Each student claims one lesson term and silently drafts: 1) one-line definition, 2) example sentence, 3) gesture.", duration: "8 min" },
      { step: "Alphabetical line-up by claimed term.", duration: "3 min" },
      { step: "Walking dictionary: in alphabetical order, each student presents term + definition + gesture.", duration: "10 min" },
      { step: "Quiz mode: teacher calls any term; the owner steps forward and the class shouts the gesture.", duration: "6 min" },
      { step: "Debrief: which definition you heard was sharper than yours?", duration: "3 min" },
    ],
    scoring_or_win: "Class self-rates dictionary completeness (1–5).",
    variations: ["Two students share an entry: one defines, one exemplifies."],
    source_note: "Cooperative-learning structure 'Numbered Heads' adapted for vocabulary.",
  },

  // ============ Matrix & Grid (Math / Logic / Reasoning) ============
  {
    id: "g-mg-01", title: "Human Coordinate Battleship", category: "Matrix & Grid",
    pitch: "Two teams hide secret ships on a body-grid and call coordinates to sink them.",
    group_size: "Two teams of 8+.", total_duration: "30 min",
    instructions: [
      { step: "Define a 6×6 floor grid by counting paces from a chosen origin.", duration: "4 min" },
      { step: "Each team secretly assigns 4 ships covering 1, 2, 3, 4 contiguous cells; record on fingers.", duration: "5 min" },
      { step: "Teams alternate calling coordinates; teacher arbitrates hits/misses; hit students kneel.", duration: "16 min" },
      { step: "Sunken ship = all students of that ship sit down; team announces which lesson rule it represented.", duration: "—" },
      { step: "Debrief: which axis convention tripped your team up?", duration: "5 min" },
    ],
    scoring_or_win: "Team that sinks all enemy ships first wins.",
    variations: ["Negative coordinates.", "Polar grid for advanced groups."],
    source_note: "Hasbro Battleship adapted as kinesthetic geometry game.",
  },
  {
    id: "g-mg-02", title: "Fermi Estimation League", category: "Matrix & Grid",
    pitch: "Order-of-magnitude estimation tournament on lesson-relevant quantities.",
    group_size: "Pairs.", total_duration: "30 min",
    instructions: [
      { step: "Teach the Fermi method: decompose, estimate each factor, multiply, round to nearest order of magnitude.", duration: "6 min" },
      { step: "Round 1 (easy): teacher poses 3 questions; pairs whisper estimate; reveal simultaneously.", duration: "8 min" },
      { step: "Round 2 (lesson-tied): 3 questions linked to the lesson; pairs must verbalize their decomposition.", duration: "9 min" },
      { step: "Round 3 (lightning): 5 questions in 5 minutes; pairs raise fingers (1–10) for exponent only.", duration: "5 min" },
      { step: "Debrief: which estimate were you most off on, and why?", duration: "2 min" },
    ],
    scoring_or_win: "Closest exponent scores 3, within one order scores 1; cumulate.",
    variations: ["Solo mode for HW prep.", "Reverse: give the answer, guess the question."],
    source_note: "Method from Enrico Fermi; classroom version in NCTM materials.",
  },
  {
    id: "g-mg-03", title: "Buzz / Fizz / Bang", category: "Matrix & Grid",
    pitch: "Count around the circle replacing multiples of three lesson-chosen numbers with sound words.",
    group_size: "Circle of any size.", total_duration: "30 min",
    instructions: [
      { step: "Class chooses 3 numbers tied to the lesson (e.g. prime, perfect, Fibonacci-relevant).", duration: "4 min" },
      { step: "Round 1: replace multiples of N1 with 'BUZZ'. Errors restart the count.", duration: "6 min" },
      { step: "Round 2: add 'FIZZ' for N2 multiples. Common multiples = 'FIZZBUZZ'.", duration: "7 min" },
      { step: "Round 3: add 'BANG' for N3, plus reverse direction every prime.", duration: "8 min" },
      { step: "Survival round: anyone who errs sits; last 3 standing win.", duration: "3 min" },
      { step: "Debrief: which composite stumped you most?", duration: "2 min" },
    ],
    scoring_or_win: "Last 3 standing in survival round.",
    variations: ["Letters instead of numbers.", "Add modular arithmetic constraints."],
    source_note: "Classic 'Fizz Buzz' playground game; programming interview staple.",
  },
  {
    id: "g-mg-04", title: "Set Theory Statues", category: "Matrix & Grid",
    pitch: "Bodies form Venn diagrams that mutate with each new attribute.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Mark three large overlapping circles on the floor with imaginary chalk.", duration: "3 min" },
      { step: "Round 1: teacher names ONE attribute per circle; students stand inside the union they belong to.", duration: "7 min" },
      { step: "Round 2: students count |A|, |B|, |C|, |A∩B|, etc. aloud; teacher writes counts in the air.", duration: "6 min" },
      { step: "Round 3: switch attributes mid-round; students must move within 5 seconds.", duration: "8 min" },
      { step: "Lesson-link round: attributes are lesson-specific (e.g. characters with X trait).", duration: "4 min" },
      { step: "Debrief: which intersection was empty? What does that tell us about the lesson?", duration: "2 min" },
    ],
    scoring_or_win: "Speed and accuracy of regrouping.",
    variations: ["4 sets requires a Karnaugh-like floor map."],
    source_note: "Standard Venn-diagram embodied math activity (NCTM).",
  },
  {
    id: "g-mg-05", title: "Algorithm Tag", category: "Matrix & Grid",
    pitch: "Tag rules are a sorting/search algorithm — playing teaches its complexity.",
    group_size: "20+ in open space.", total_duration: "30 min",
    instructions: [
      { step: "Each student gets a secret number 1–N by silent finger-count.", duration: "3 min" },
      { step: "Round 1 (bubble sort): adjacent pairs compare; swap if out of order. Repeat until sorted line forms.", duration: "8 min" },
      { step: "Round 2 (binary search): line stays sorted; teacher calls a target; designated 'searcher' tags only the midpoint, then halves.", duration: "8 min" },
      { step: "Round 3 (quicksort): pick a pivot student; others move left/right; recurse with sub-pivots.", duration: "8 min" },
      { step: "Debrief: count comparisons made. Compare to Big-O on the board (verbally).", duration: "3 min" },
    ],
    scoring_or_win: "Fewest comparisons wins.",
    variations: ["Time each algorithm; chart on the wall as gestures."],
    source_note: "CS Unplugged sorting networks (csunplugged.org), zero-equipment variant.",
  },
  {
    id: "g-mg-06", title: "Probability Showdown", category: "Matrix & Grid",
    pitch: "Hand-signal coin flips and finger dice drive a 30-minute probability tournament.",
    group_size: "Pairs.", total_duration: "30 min",
    instructions: [
      { step: "Teach the protocols: hand-behind-back = coin (palm up/down); fingers 1–5 = die.", duration: "5 min" },
      { step: "Game 1 (coin streaks): predict longest streak in 20 flips; closest wins.", duration: "7 min" },
      { step: "Game 2 (sum war): each pair throws two finger-dice; higher sum wins; tally over 15 rounds.", duration: "8 min" },
      { step: "Game 3 (Monty Hall): role-play 10 rounds with three students as doors; track switch vs. stay outcomes on the board verbally.", duration: "8 min" },
      { step: "Debrief: which outcome was furthest from theoretical? Why?", duration: "2 min" },
    ],
    scoring_or_win: "Cumulative wins across games.",
    variations: ["Add bias: weighted coin via hand-position rule."],
    source_note: "Combines classic probability paradoxes; Monty Hall via Marilyn vos Savant.",
  },
  {
    id: "g-mg-07", title: "Geometric Twister", category: "Matrix & Grid",
    pitch: "Body geometry challenges — angles, polygons, symmetry — built in teams.",
    group_size: "Teams of 4–6.", total_duration: "30 min",
    instructions: [
      { step: "Demonstrate body-angle basics: arm = ray, body = vertex.", duration: "4 min" },
      { step: "Round 1: teacher calls an angle (45°, 135°…); each team produces it with two students.", duration: "6 min" },
      { step: "Round 2: teacher calls a polygon; team builds it floor-down using all members; class audits edges.", duration: "8 min" },
      { step: "Round 3: 3D challenge — tetrahedron, cube edge frame, triangular prism.", duration: "8 min" },
      { step: "Final: symmetry challenge — team builds a shape with bilateral symmetry across an imaginary axis.", duration: "2 min" },
      { step: "Debrief: which property was hardest to satisfy?", duration: "2 min" },
    ],
    scoring_or_win: "Audit points per challenge; highest team wins.",
    variations: ["Add interior-angle-sum verification."],
    source_note: "PE Central + NCTM kinesthetic geometry hybrid.",
  },
  {
    id: "g-mg-08", title: "Logic Grid Live", category: "Matrix & Grid",
    pitch: "Students embody a logic puzzle and physically deduce the solution.",
    group_size: "Groups of 4–5.", total_duration: "30 min",
    instructions: [
      { step: "Teacher reads a 4×4 logic puzzle aloud twice (e.g. who lives where, owns what).", duration: "5 min" },
      { step: "Each student in a group represents one row; they hold attribute cards as fingers.", duration: "5 min" },
      { step: "Group works through the clues, physically swapping positions to satisfy each.", duration: "15 min" },
      { step: "Group announces solution; teacher verifies; first correct group narrates their deduction chain.", duration: "3 min" },
      { step: "Debrief: which clue was most informative? Why?", duration: "2 min" },
    ],
    scoring_or_win: "First correct group wins; bonus for cleanest deduction narration.",
    variations: ["5×5 puzzles for advanced.", "Solo silent mode."],
    source_note: "Zebra/Einstein puzzle format, embodied per Kagan 'Stand-Up Hand-Up'.",
  },
  {
    id: "g-mg-09", title: "Estimation Auction", category: "Matrix & Grid",
    pitch: "Bid on estimation problems with 100 imaginary coins; closest answer takes the pot.",
    group_size: "Pairs or triads.", total_duration: "30 min",
    instructions: [
      { step: "Each team starts with 100 verbal coins. Teacher posts 8 estimation problems.", duration: "4 min" },
      { step: "Per problem: teams whisper-bid (1–20 coins) before estimating.", duration: "—" },
      { step: "Lowest bidder must estimate first; others must bracket above or below.", duration: "16 min" },
      { step: "Closest estimate wins the bid pot; teacher tracks coin totals aloud.", duration: "—" },
      { step: "Final problem: blind double-or-nothing.", duration: "6 min" },
      { step: "Debrief: which bid strategy worked?", duration: "4 min" },
    ],
    scoring_or_win: "Highest coin total wins.",
    variations: ["Include unit-conversion problems."],
    source_note: "Market-mechanism teaching method, adapted from Estimation 180 (Andrew Stadel).",
  },
  {
    id: "g-mg-10", title: "Pattern Detective", category: "Matrix & Grid",
    pitch: "One student is the rule-keeper; the class proposes sequences to crack the rule.",
    group_size: "Whole class + 1 rule-keeper.", total_duration: "30 min",
    instructions: [
      { step: "Rule-keeper invents a numeric rule and shows it to the teacher only.", duration: "3 min" },
      { step: "Class proposes triples; rule-keeper answers 'fits' or 'fails'. Triples are spoken aloud only.", duration: "12 min" },
      { step: "Anyone may guess the rule; wrong guess costs the class one of 5 lives.", duration: "—" },
      { step: "Rotate two more rule-keepers with progressively harder rules.", duration: "12 min" },
      { step: "Debrief: which question types narrowed the hypothesis space fastest?", duration: "3 min" },
    ],
    scoring_or_win: "Class wins if it cracks each rule with lives remaining.",
    variations: ["Use Wason 2-4-6 task explicitly for confirmation-bias discussion."],
    source_note: "Adapted from Peter Wason's 2-4-6 task in cognitive psychology.",
  },
  {
    id: "g-mg-11", title: "Modular Clock Tag", category: "Matrix & Grid",
    pitch: "Floor clock with modular arithmetic — students leap by step sizes to teach modular cycles.",
    group_size: "12+ students.", total_duration: "30 min",
    instructions: [
      { step: "12 students stand in a clock-circle, each holding a number 0–11. The rest are 'leapers'.", duration: "4 min" },
      { step: "Teacher calls a step size k. Leapers start at 0 and walk +k positions each beat.", duration: "8 min" },
      { step: "Record visited positions aloud; class names the cycle length.", duration: "6 min" },
      { step: "Predict: for which k values does the cycle visit all 12? Test conjectures.", duration: "8 min" },
      { step: "Switch modulus to 7 (form a heptagon) and repeat.", duration: "2 min" },
      { step: "Debrief: connect to gcd(k, n).", duration: "2 min" },
    ],
    scoring_or_win: "Class derives the gcd rule by play.",
    variations: ["Use musical beats instead of steps."],
    source_note: "Embodied number theory used in math circles.",
  },
  {
    id: "g-mg-12", title: "Mental Math Marathon", category: "Matrix & Grid",
    pitch: "Relay rounds of escalating mental math, building stamina and verbal fluency.",
    group_size: "Teams of 5.", total_duration: "30 min",
    instructions: [
      { step: "Teach mental-math tactics (chunking, complements to 10, distributive).", duration: "5 min" },
      { step: "Round 1: 2-digit add/subtract relay; each team-member answers one before passing.", duration: "6 min" },
      { step: "Round 2: 2-digit × 1-digit multiplication.", duration: "6 min" },
      { step: "Round 3: percentages and fractions of whole numbers.", duration: "6 min" },
      { step: "Lightning final: order of operations word-problems.", duration: "5 min" },
      { step: "Debrief: which tactic carried the team?", duration: "2 min" },
    ],
    scoring_or_win: "Most correct in time wins.",
    variations: ["Differentiate by giving each member a difficulty tier."],
    source_note: "Inspired by Jo Boaler's 'Number Talks' fluency routines.",
  },
  {
    id: "g-mg-13", title: "Conjecture Court", category: "Matrix & Grid",
    pitch: "Mock trial of a mathematical or logical conjecture from the lesson.",
    group_size: "Whole class with assigned roles.", total_duration: "30 min",
    instructions: [
      { step: "Assign roles: 2 prosecutors (counter-examples), 2 defense (proof attempts), judge, jury.", duration: "4 min" },
      { step: "Teacher reads the conjecture. 5-minute prep on each side.", duration: "5 min" },
      { step: "Opening statements (2 min each side).", duration: "4 min" },
      { step: "Three rounds of examples vs. counter-examples; jury asks one question each round.", duration: "12 min" },
      { step: "Closing arguments + jury verbal verdict.", duration: "3 min" },
      { step: "Debrief: was the verdict mathematically correct? Where did rhetoric outrun proof?", duration: "2 min" },
    ],
    scoring_or_win: "Jury vote settles the trial.",
    variations: ["Add an appeals round with a new conjecture."],
    source_note: "Inquiry-based math instruction (IBL Math).",
  },

  // ============ Circuit & Spark (High-energy, kinesthetic, energizers) ============
  {
    id: "g-cs-01", title: "Knowledge Capture the Flag", category: "Circuit & Spark",
    pitch: "Two teams race to 'capture' lesson facts placed in opposite corners by answering challenges.",
    group_size: "Two teams of 8+.", total_duration: "30 min",
    instructions: [
      { step: "Define territories and 'jails'. Each team places 5 imaginary flags (lesson facts) in their corner.", duration: "5 min" },
      { step: "Players cross the centre line to challenge an opponent: defender poses a lesson question; attacker must answer correctly to avoid jail.", duration: "—" },
      { step: "A jailed player is freed when a teammate tags them AND answers a question successfully.", duration: "—" },
      { step: "Play three 7-minute rounds with teacher as referee.", duration: "21 min" },
      { step: "Debrief: which facts were toughest to defend? Why?", duration: "4 min" },
    ],
    scoring_or_win: "Capture all flags or hold the lead at time.",
    variations: ["Indoor low-mobility: walk-only.", "Add a 'safe zone'."],
    source_note: "Classic capture-the-flag with academic challenge layer.",
  },
  {
    id: "g-cs-02", title: "Rock-Paper-Scissors Evolution", category: "Circuit & Spark",
    pitch: "Whole-room RPS ladder where each win evolves you to the next lesson stage.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Define 5 evolution stages tied to the lesson (e.g. egg → larva → pupa → adult → champion).", duration: "4 min" },
      { step: "Everyone starts as stage 1. Find a same-stage partner, play RPS best-of-1; winner evolves, loser stays.", duration: "—" },
      { step: "Champions stand on chairs and cheer. Play continues for 8 minutes.", duration: "8 min" },
      { step: "Round 2: each evolution requires correctly answering a lesson question posed by an evolved teacher-assistant.", duration: "10 min" },
      { step: "Round 3: champions become 'bosses' who can devolve challengers who lose.", duration: "6 min" },
      { step: "Debrief: how did the question barrier change strategy?", duration: "2 min" },
    ],
    scoring_or_win: "Final count of champions.",
    variations: ["Use lesson-specific gestures instead of RPS."],
    source_note: "Adapted from Improv-Encyclopedia 'Evolution' game.",
  },
  {
    id: "g-cs-03", title: "Four Corners Debate", category: "Circuit & Spark",
    pitch: "Move to one of four corners to declare a stance; defend or migrate after each round.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Label four corners: Strongly Agree, Agree, Disagree, Strongly Disagree.", duration: "2 min" },
      { step: "Teacher reads statement 1; students walk to a corner; each corner gives a 60-second pitch.", duration: "6 min" },
      { step: "Open migration: anyone may switch corners and must explain why aloud.", duration: "—" },
      { step: "Repeat with 4 statements, escalating in nuance.", duration: "20 min" },
      { step: "Debrief: which statement caused most migration?", duration: "2 min" },
    ],
    scoring_or_win: "No score — track migration patterns aloud.",
    variations: ["Add a fifth 'undecided' centre spot."],
    source_note: "Standard four-corners discussion strategy (Kagan).",
  },
  {
    id: "g-cs-04", title: "Stand Up If…", category: "Circuit & Spark",
    pitch: "Lightning quiz where students stand only if the statement applies — fast, physical, formative.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Demo rules: stand if true, sit if false, kneel if unsure. No talking until 'go'.", duration: "3 min" },
      { step: "Teacher fires 20 lesson statements at 30s pace.", duration: "10 min" },
      { step: "After each, one standing student justifies in 10 seconds.", duration: "—" },
      { step: "Round 2: students compose statements in pairs; pairs take turns running it.", duration: "13 min" },
      { step: "Debrief: which statement split the room?", duration: "4 min" },
    ],
    scoring_or_win: "No score — formative thermometer.",
    variations: ["Use thumbs-up/sideways/down for tight spaces."],
    source_note: "Common AfL routine (Dylan Wiliam 'Embedded Formative Assessment').",
  },
  {
    id: "g-cs-05", title: "Lesson Relay Race", category: "Circuit & Spark",
    pitch: "Relay where each leg is answering a lesson question correctly to pass the (mimed) baton.",
    group_size: "Teams of 5–8.", total_duration: "30 min",
    instructions: [
      { step: "Set a start line and turnaround point.", duration: "3 min" },
      { step: "Runner 1 sprints to teacher; answers a question; if correct, runs back and tags Runner 2.", duration: "—" },
      { step: "Wrong answer: runner does 5 jumping jacks and retries with a new question.", duration: "—" },
      { step: "Three full relay rounds, escalating question difficulty.", duration: "22 min" },
      { step: "Debrief: which question type slowed your team?", duration: "5 min" },
    ],
    scoring_or_win: "First team to finish each round; cumulate.",
    variations: ["Walking-pace for indoor.", "Pair-runners for support."],
    source_note: "Classic PE relay overlaid with academic gate.",
  },
  {
    id: "g-cs-06", title: "Ninja (Lesson Edition)", category: "Circuit & Spark",
    pitch: "Circle ninja-strike game where each strike requires shouting a lesson term.",
    group_size: "8–15 in a circle.", total_duration: "30 min",
    instructions: [
      { step: "Demo: ninja stance, single freeze-frame strike to eliminate adjacent player's hand.", duration: "5 min" },
      { step: "Each strike must be preceded by shouting a lesson term not used yet.", duration: "—" },
      { step: "Players are out when both hands are tagged.", duration: "20 min" },
      { step: "Final two play a duel with bonus rule: term must be a definition spoken in full.", duration: "3 min" },
      { step: "Debrief: which terms surfaced most? Which were forgotten?", duration: "2 min" },
    ],
    scoring_or_win: "Last ninja standing.",
    variations: ["Quiet mode for shared spaces — whispered terms."],
    source_note: "Camp/improv 'Ninja' game with academic gate.",
  },
  {
    id: "g-cs-07", title: "Mass Hide-and-Speak", category: "Circuit & Spark",
    pitch: "Players hide in pairs anywhere in sight; whisper-recite lesson facts to win freedom.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "One seeker counts to 30; pairs hide in visible spots within the room.", duration: "4 min" },
      { step: "When found, pair must whisper-recite a lesson fact in unison to escape; otherwise frozen for 60s.", duration: "—" },
      { step: "Frozen pairs are revived by another pair whispering a different fact.", duration: "—" },
      { step: "Three 7-minute rounds with rotating seekers.", duration: "21 min" },
      { step: "Debrief: which facts came up most often? Which were rare?", duration: "5 min" },
    ],
    scoring_or_win: "Most facts recited correctly across rounds.",
    variations: ["Outdoor version with bigger boundaries."],
    source_note: "Classic hide-and-seek with academic recall gate.",
  },
  {
    id: "g-cs-08", title: "Energizer Tabata", category: "Circuit & Spark",
    pitch: "20-second movement bursts paired with 10-second lesson recall — eight rounds.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Teach 8 movements (squat, jumping jack, march, etc.). Demo a 4-min Tabata block.", duration: "6 min" },
      { step: "Block 1: 8 rounds. During each 10s rest, each row shouts a lesson fact in order.", duration: "5 min" },
      { step: "Block 2: rest periods become 10s think-pair-share whispers on a teacher prompt.", duration: "5 min" },
      { step: "Block 3: rest periods are 'I wonder…' question generation.", duration: "5 min" },
      { step: "Block 4: rest periods are answers to the questions from Block 3.", duration: "5 min" },
      { step: "Debrief: which question stayed unanswered?", duration: "4 min" },
    ],
    scoring_or_win: "No score — completion.",
    variations: ["Seated chair-Tabata for low-mobility groups."],
    source_note: "Tabata protocol (Izumi Tabata) adapted as brain-body interleave.",
  },
  {
    id: "g-cs-09", title: "Walking Gallery", category: "Circuit & Spark",
    pitch: "The class becomes a walking museum: each student is a living exhibit of one lesson idea.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Each student selects one lesson idea and crafts a 30-second exhibit speech + pose.", duration: "8 min" },
      { step: "Half the class poses as exhibits; the other half walks the gallery in pairs.", duration: "8 min" },
      { step: "Switch roles.", duration: "8 min" },
      { step: "Curator's pick: each walker nominates the most memorable exhibit; class votes.", duration: "4 min" },
      { step: "Debrief: which exhibits formed unexpected pairings of ideas?", duration: "2 min" },
    ],
    scoring_or_win: "Class chooses top 3 exhibits.",
    variations: ["Add audio guides (whispered narration)."],
    source_note: "Variant of 'Gallery Walk' protocol from National School Reform Faculty.",
  },
  {
    id: "g-cs-10", title: "Human Knot Puzzle", category: "Circuit & Spark",
    pitch: "Untangle a human knot while solving lesson riddles — pure cooperation.",
    group_size: "Groups of 8–10.", total_duration: "30 min",
    instructions: [
      { step: "Groups form a circle, reach across, grab two different hands. No double-partners.", duration: "5 min" },
      { step: "Group must untangle without releasing grips. Every 90 seconds the teacher asks a lesson riddle; correct answer earns one allowed grip-release.", duration: "20 min" },
      { step: "Successful groups celebrate; struggling groups debrief their strategy aloud.", duration: "3 min" },
      { step: "Debrief: what communication patterns worked?", duration: "2 min" },
    ],
    scoring_or_win: "Untangled circle wins.",
    variations: ["Silent mode — only gestures."],
    source_note: "Classic team-building 'Human Knot' with academic earn-mechanic.",
  },
  {
    id: "g-cs-11", title: "Stop-the-Beat Quiz", category: "Circuit & Spark",
    pitch: "Music-less musical chairs where stopping requires answering a lesson question.",
    group_size: "10–25.", total_duration: "30 min",
    instructions: [
      { step: "Form a moving circle. Teacher claps a beat; class moves clockwise.", duration: "4 min" },
      { step: "Teacher stops clapping and points to a student who must answer a lesson question in 5 seconds.", duration: "—" },
      { step: "Correct answer: student rejoins. Wrong: student becomes a 'beat-keeper' and stands inside the circle to clap.", duration: "—" },
      { step: "Three 7-minute rounds.", duration: "21 min" },
      { step: "Debrief: which question type stalled the most students?", duration: "5 min" },
    ],
    scoring_or_win: "Last circle-walkers standing.",
    variations: ["Beat-keepers can 'rescue' by answering bonus questions."],
    source_note: "Musical-chairs format with academic gating; common ELT practice.",
  },
  {
    id: "g-cs-12", title: "Speed-Dating Review", category: "Circuit & Spark",
    pitch: "Two facing rows; each pair has 3 minutes to teach each other a lesson concept, then rotate.",
    group_size: "Even number; rows of 6–10.", total_duration: "30 min",
    instructions: [
      { step: "Assign each student one lesson concept (10 total minimum).", duration: "5 min" },
      { step: "Pair across rows. 90s per partner: A teaches B. Then 90s: B teaches A. Bell, rotate one seat.", duration: "—" },
      { step: "Six rotations.", duration: "18 min" },
      { step: "Whole-class quiz: teacher fires 10 concepts; class shouts a partner's name who taught it well.", duration: "5 min" },
      { step: "Debrief: which concept did you find easiest to teach?", duration: "2 min" },
    ],
    scoring_or_win: "Most-named teachers earn a snap-round.",
    variations: ["Triads for odd numbers."],
    source_note: "Speed-dating EFL protocol popularised by Paul Nation.",
  },

  // ============ Anchor & Lock (Closure / Review / Reflection) ============
  {
    id: "g-al-01", title: "30-Minute Socratic Seminar", category: "Anchor & Lock",
    pitch: "A circle of inquiry that locks today's lesson into questions, not answers.",
    group_size: "10–20 in a circle.", total_duration: "30 min",
    instructions: [
      { step: "Teacher poses ONE open question. Talking piece (imaginary) passes around once: every student gives one sentence.", duration: "8 min" },
      { step: "Free flow: students speak only after restating the prior speaker's idea. Max 30s per turn.", duration: "12 min" },
      { step: "Silent reflection: 60 seconds of stillness.", duration: "1 min" },
      { step: "Closing whip: each student names one unresolved question they leave with.", duration: "7 min" },
      { step: "Debrief: which unresolved question is most worth pursuing?", duration: "2 min" },
    ],
    scoring_or_win: "No score — pursuit of better questions.",
    variations: ["Fishbowl with inner/outer circles."],
    source_note: "Socratic seminar; Paideia Group / NSRF protocols.",
  },
  {
    id: "g-al-02", title: "Concept Mapping Aloud", category: "Anchor & Lock",
    pitch: "Build a class concept map verbally — each connection narrated and defended.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Brainstorm aloud: students shout 15 lesson terms; teacher 'pins' each in air-space.", duration: "5 min" },
      { step: "Volunteers walk the air-space and draw connection lines, narrating: 'X relates to Y because…' Class signals approval.", duration: "15 min" },
      { step: "Hierarchy round: class assigns each term a level (1–5 abstraction) by raised fingers.", duration: "5 min" },
      { step: "Cluster round: students physically group themselves under chosen terms; clusters defend their grouping.", duration: "3 min" },
      { step: "Debrief: which connection surprised you?", duration: "2 min" },
    ],
    scoring_or_win: "Class agrees on top-3 'spine' connections.",
    variations: ["Pair version for shy classes."],
    source_note: "Concept-mapping (Joseph Novak) without paper.",
  },
  {
    id: "g-al-03", title: "Exit Interview Pairs", category: "Anchor & Lock",
    pitch: "Pairs interview each other on what they learned, like leaving a job — structured and serious.",
    group_size: "Pairs.", total_duration: "30 min",
    instructions: [
      { step: "Pose 4 interview questions: What did you accomplish? Where did you struggle? What surprised you? What's your next goal?", duration: "5 min" },
      { step: "Round 1: A interviews B for 6 minutes. No interruptions; only follow-up questions allowed.", duration: "6 min" },
      { step: "Swap. B interviews A.", duration: "6 min" },
      { step: "Pairs synthesize each other's best insight into one sentence.", duration: "5 min" },
      { step: "Whole class share-out: each pair offers one synthesis.", duration: "6 min" },
      { step: "Debrief: was someone else's articulation of your learning clearer than your own?", duration: "2 min" },
    ],
    scoring_or_win: "No score — clarity of insight.",
    variations: ["Triad with observer note-taker (mental notes only)."],
    source_note: "Variant of Critical Friends Group consultancy protocol.",
  },
  {
    id: "g-al-04", title: "Whip-Around Wrap", category: "Anchor & Lock",
    pitch: "Rapid round-the-room single-sentence reflections with escalating prompts.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Round 1 prompt: 'One thing I now know'. Each student responds in 5 seconds.", duration: "5 min" },
      { step: "Round 2: 'One thing I'm still confused about'.", duration: "5 min" },
      { step: "Round 3: 'One way I'd teach this to my younger sibling'.", duration: "6 min" },
      { step: "Round 4: 'One question I'd ask the author/expert'.", duration: "6 min" },
      { step: "Round 5: 'One word that captures today'. Class chants the final 5 words together.", duration: "6 min" },
      { step: "Debrief: which round revealed the most?", duration: "2 min" },
    ],
    scoring_or_win: "No score — completeness of voice.",
    variations: ["Stand & sit pacing for energy."],
    source_note: "Whip-around discussion protocol (NSRF).",
  },
  {
    id: "g-al-05", title: "Headlines, Tweets & Bumper Stickers", category: "Anchor & Lock",
    pitch: "Three escalating compression challenges — capture the lesson in three formats.",
    group_size: "Triads.", total_duration: "30 min",
    instructions: [
      { step: "Triad drafts a 15-word headline of today's lesson (spoken).", duration: "7 min" },
      { step: "Compress to a 12-word tweet with a hook.", duration: "7 min" },
      { step: "Compress to a 5-word bumper sticker.", duration: "8 min" },
      { step: "Each triad performs all three formats; class snaps for best of each.", duration: "6 min" },
      { step: "Debrief: which compression forced the sharpest thinking?", duration: "2 min" },
    ],
    scoring_or_win: "Class snap-vote per format.",
    variations: ["Add a 'haiku' format."],
    source_note: "Project Zero 'Headlines' routine extended.",
  },
  {
    id: "g-al-06", title: "I Used To Think… Now I Think…", category: "Anchor & Lock",
    pitch: "Trace conceptual change aloud with the Project Zero routine, extended into pair coaching.",
    group_size: "Pairs → whole class.", total_duration: "30 min",
    instructions: [
      { step: "Individuals silently form their 'I used to think…' / 'Now I think…' statements (4 min).", duration: "4 min" },
      { step: "Pair share: each partner gives a 60-second statement; partner asks 2 probing questions.", duration: "10 min" },
      { step: "Mix and re-pair; second partner must paraphrase your shift before sharing their own.", duration: "10 min" },
      { step: "Whole-class share-out: 4 volunteers narrate their shift.", duration: "4 min" },
      { step: "Debrief: was the shift in content or in confidence?", duration: "2 min" },
    ],
    scoring_or_win: "No score — visibility of conceptual change.",
    variations: ["Add 'And I wonder…' as a third stem."],
    source_note: "Project Zero 'I Used To Think… Now I Think…' routine.",
  },
  {
    id: "g-al-07", title: "3-2-1 Tower", category: "Anchor & Lock",
    pitch: "Each student delivers 3 takeaways, 2 questions, 1 application — stacked into a class 'tower' of voices.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Demo the 3-2-1 stems clearly.", duration: "3 min" },
      { step: "Pairs draft theirs (6 minutes).", duration: "6 min" },
      { step: "Stacking round: students stand in a line; each speaks their 3 takeaways one after another, then 2 questions, then 1 application.", duration: "12 min" },
      { step: "Class lists the most repeated takeaway, most distinctive question, most ambitious application.", duration: "7 min" },
      { step: "Debrief: which 'application' is the class actually likely to act on?", duration: "2 min" },
    ],
    scoring_or_win: "Class consensus on top items.",
    variations: ["Use 5-3-1 for advanced or long lessons."],
    source_note: "Classic 3-2-1 exit routine (Allyn & Bacon).",
  },
  {
    id: "g-al-08", title: "Snowball Reflection", category: "Anchor & Lock",
    pitch: "Reflections balled up (verbally), tossed, unfolded, and read aloud — anonymity drives honesty.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Each student silently composes one anonymous reflection sentence about the lesson.", duration: "5 min" },
      { step: "Lining up, each student whispers their sentence to a 'scribe' who memorizes it.", duration: "8 min" },
      { step: "Scribes shuffle and read sentences aloud to the class in random order.", duration: "10 min" },
      { step: "Class discusses themes that emerged anonymously.", duration: "5 min" },
      { step: "Debrief: did anonymity surface something different?", duration: "2 min" },
    ],
    scoring_or_win: "No score — surfacing of honest reflections.",
    variations: ["Use the imaginary 'snowball toss' as a movement break."],
    source_note: "Adaptation of Snowball Discussion (Faculty Focus).",
  },
  {
    id: "g-al-09", title: "Lesson Time Capsule", category: "Anchor & Lock",
    pitch: "Compose a verbal time capsule for next year's class about today's lesson.",
    group_size: "Triads.", total_duration: "30 min",
    instructions: [
      { step: "Each triad agrees on 5 items to put in the capsule: 1 fact, 1 method, 1 warning, 1 joke, 1 hope.", duration: "12 min" },
      { step: "Triads perform their capsule as a 90-second monologue addressed to 'next year's class'.", duration: "10 min" },
      { step: "Class votes the canonical capsule; canonical items are recited together to 'seal' it.", duration: "6 min" },
      { step: "Debrief: which warning is most worth heeding?", duration: "2 min" },
    ],
    scoring_or_win: "Class vote settles the canonical capsule.",
    variations: ["Address the capsule to past self instead."],
    source_note: "Reflective writing protocol adapted to oral form.",
  },
  {
    id: "g-al-10", title: "Two Stars and a Wish Carousel", category: "Anchor & Lock",
    pitch: "Each student gives two specific praises and one improvement wish to two classmates' learning.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Model two stars (specific) and one wish (actionable).", duration: "4 min" },
      { step: "Round 1: pairs swap their best contribution of today; each gives the other 2 stars + 1 wish.", duration: "10 min" },
      { step: "Rotate partners; repeat with new partner using a different contribution.", duration: "10 min" },
      { step: "Whole-class harvest: 4 volunteers share the most useful wish they received.", duration: "4 min" },
      { step: "Debrief: was praise easier than the wish? Why?", duration: "2 min" },
    ],
    scoring_or_win: "No score — quality of feedback.",
    variations: ["Use stars only for novice classes."],
    source_note: "Two Stars and a Wish feedback technique (Dylan Wiliam).",
  },
  {
    id: "g-al-11", title: "Connections Web", category: "Anchor & Lock",
    pitch: "Students link the lesson to prior knowledge using a physical web of pointing — no string needed.",
    group_size: "Circle of 10–25.", total_duration: "30 min",
    instructions: [
      { step: "Stand in a circle. Teacher seeds with one lesson concept aloud.", duration: "3 min" },
      { step: "Whoever has a connection points to the speaker, names the connection, and becomes the new speaker.", duration: "12 min" },
      { step: "Web rule: each student may receive a pointer only twice. After that, must yield.", duration: "—" },
      { step: "Reverse round: web 'unravels' — each student must recall who pointed at them and the connection named.", duration: "10 min" },
      { step: "Debrief: which connection felt strongest?", duration: "5 min" },
    ],
    scoring_or_win: "Class recalls 80%+ of connections.",
    variations: ["Add a category constraint each round."],
    source_note: "Council-circle and 'web of connections' SEL practice.",
  },
  {
    id: "g-al-12", title: "Mindful Lesson Body-Scan", category: "Anchor & Lock",
    pitch: "Calm closure — guided body-scan with lesson cues anchored to each body region.",
    group_size: "Whole class.", total_duration: "30 min",
    instructions: [
      { step: "Sit comfortably; eyes closed or soft gaze. Teacher leads three slow breaths.", duration: "3 min" },
      { step: "Body-scan from head to feet (8 regions); at each region, teacher reads a one-line lesson cue and pauses 20 seconds for silent visualisation.", duration: "16 min" },
      { step: "Open eyes. Pair share: which cue stayed most vivid?", duration: "6 min" },
      { step: "Final whip: one word each, eyes open.", duration: "3 min" },
      { step: "Debrief: how did stillness change the recall?", duration: "2 min" },
    ],
    scoring_or_win: "No score — calm coherent closure.",
    variations: ["Walking meditation variant for high-energy classes."],
    source_note: "Mindfulness in Schools Project '.b' curriculum.",
  },
];

export const GAME_CATEGORIES: Category[] = ["Echo & Flow", "Matrix & Grid", "Circuit & Spark", "Anchor & Lock"];
